### ISSUE TITLE
Adding Feature: Ignore URL Patterns

### ISSUE THREAD

**Issue by StellaJung-Student** [zjjiang2/project-checkurl#13]
Hello, @zjjiang2.

Can I work on this issue?

**Comment by zjjiang2** [comment]
Sure, feel free to do anything.

**Comment by StellaJung-Student** [comment]
I pushed this in [my repository](https://github.com/StellaJung-Student/project-checkurl/tree/issue-13).

Here is my test result and I also attached test file.
![image](https://user-images.githubusercontent.com/59578350/96193505-4b2efd80-0f16-11eb-87a6-ed05dce8dedc.png)
![image](https://user-images.githubusercontent.com/59578350/96193532-5b46dd00-0f16-11eb-8dd5-e065cd448ea6.png)

Please let me know if I am wrong or any suggestion to improve

**Comment by zjjiang2** [comment]
looks fine to me.

**Comment by StellaJung-Student** [comment]
Just want to say that you should do next step with my forked repository~ 
My repository is https://github.com/StellaJung-Student/project-checkurl.git and branch is issue-13.

**Comment by StellaJung-Student** [comment]
Any update on my task?

**Comment by zjjiang2** [comment]
Is there supposed to be a Pull Request that I don't see?

**Comment by zjjiang2** [comment]
@StellaJung-Student  It is done, please double check the main repo on your end. 👍

**Comment by StellaJung-Student** [comment]
@zjjiang2 Did you modify anything on my code? it means that you should create new branch like issue-13-fix. Otherwise, I don't need to do anything and you can merge my code to your master and push to your git repo and close this issue.

**Comment by zjjiang2** [comment]
I think I already merged it.

**Comment by StellaJung-Student** [comment]
It sounds very good~ Then, you can close this issue :)
